### ISSUE TITLE
Doesn’t seem to work on iPad Mini 2

### ISSUE THREAD

**Issue by ibrahimk157** [raspberryenvoie/piRa1n#1]
Hello,

I have piRa1n installed on my raspberry pi 4B 4GB RAM (running raspbian buster lite). And it’s been working perfectly with ny iPhone X!

I recently tried it out with my iPad Mini 2 (Cellular) and it doesn’t seem to work at all. I plug in the iPad Mini 2 to the raspberry pi and throw it into DFU mode, and nothing happens!

Happens in both iOS 13.4.1 and 13.5 (both versions worked on the iPhone X with pira1n)

Thanks

**Comment by ibrahimk157** [comment]
Update: I just tried running checkra1n manually, and it throws in a usb error -77 even though i have no passcode.

It also throws this error: “Failed to get string descriptor: LIBUSB_ERROR_TIMEOUT”

Guess this is a bug report for checkra1n then

**Comment by raspberryenvoie** [comment]
Hi ibrahimk157!
I'm glad piRa1n works! I found [this](https://github.com/checkra1n/BugTracker/issues/778), I hope you'll find a fix to your issue. Let me know if you find a solution.
Have a nice day!

**Comment by ibrahimk157** [comment]
Further update: apparently A7 support on checkra1n’s newer versions on linux is messed up. No one is able to get it to work properly. Only the mac version works for A7. Not really a pira1n issue at all.

**Comment by raspberryenvoie** [comment]
Thanks for the update! I'll close this issue.
