### ISSUE TITLE
Iphone 8+ stuck on apple logo booting

### ISSUE THREAD

**Issue by lillithrosepup** [raspberryenvoie/piRa1n#2]
I have installed piRa1n on my bananapi m2 zero and whenever i go into dfu mode, it starts jailbreaking like normal, but after it says booting it just goes to the apple logo and is stuck like that until I do a hard reset. Is there any chance you csn help or chould I ask the checkra1n devs?

**Comment by raspberryenvoie** [comment]
Hi AidenR449!
Try to manually jailbreak like on macOS and let me know if it works.
Type this command in the terminal: `sudo systemctl stop piRa1n.service && cd $HOME/piRa1n && sudo ./piRa1n`.\
Have a nice day!

**Comment by raspberryenvoie** [comment]
Idk why I closed this issue sorry. Did you find a solution?

**Comment by lillithrosepup** [comment]
I have not found a solution, but it is not needed. I now have something on
my phone that cant be closed, so I can't risk jailbreaking it because of
constant resprings. I still have the pi/sd card from my project, if it
would help you to examine it

**Comment by raspberryenvoie** [comment]
I believe it's a checkra1n issue.

**Comment by profitsboy** [comment]
what’s username password?

**Comment by raspberryenvoie** [comment]
The username and password of piRa1n-OS? It's pi and jailbreak\
It's written in the [wiki](https://github.com/raspberryenvoie/piRa1n/wiki/Install-piRa1n-on-a-Raspberry-Pi-4) and in the readme.md of piRa1n-OS

**Comment by secret223** [comment]
The game

**Comment by secret223** [comment]
The box

**Comment by raspberryenvoie** [comment]
> The username and password of piRa1n-OS? It's pi and jailbreak\
> 
> It's written in the [wiki](https://github.com/raspberryenvoie/piRa1n/wiki/Install-piRa1n-on-a-Raspberry-Pi-4) and in the readme.md of piRa1n-OS

If you've used piRa1n-OS, these are the username and password. Otherwise if you installed piRa1n using the manual method, the user is ˋpì and the password is ˋraspberry`

**Comment by raspberryenvoie** [comment]
If you have a problem please open a separate issue

**Comment by profitsboy** [comment]
i also have your situation too. but when i install the correct version . it is all done

**Comment by raspberryenvoie** [comment]
I'm closing this issue since "Iphone 8+ stuck on apple logo booting" is a checkra1n bug. @prophet-l30n and @secret223 open a separate issue if you have a problem.
