### ISSUE TITLE
Auto recover mode option not working on BPI Zero W

### ISSUE THREAD

**Issue by gilshahar7** [raspberryenvoie/piRa1n#3]
Hey, i have updated the piRa1n on my BPI Zero W and it seems like it wont kick the device into recovery mode as soon as i plug it in.

it just asks to trust the device, after entering my passcode nothing happens.

Edit: maybe its possible to add a button to the web UI to enter safemode manually? i am connected to my iPhone's hotspot so its convenient

**Comment by raspberryenvoie** [comment]
Hi, could you tell me what the following commands output please?
```
ideviceenterrecovery
irecovery
```
>Edit: maybe its possible to add a button to the web UI to enter safemode manually? i am connected to my iPhone's hotspot so its convenient

Do you mean enter recovery mode?

**Comment by gilshahar7** [comment]
Oops yes, recovery mode.

I will connect the BPI to my home network tomorow to give you the output of those commands.

**Comment by gilshahar7** [comment]
Both commands are not found.

**Comment by raspberryenvoie** [comment]
Manually install them:
```
sudo apt-get install git usbmuxd libimobiledevice6 libimobiledevice-utils build-essential checkinstall git autoconf automake libtool-bin libreadline-dev libusb-1.0-0-dev libusbmuxd-tools sshpass -y
cd /home/pi/
# Compile libirecovery
git clone https://github.com/libimobiledevice/libirecovery.git
cd libirecovery
./autogen.sh
cd /home/pi/libirecovery/
make
sudo make install
sudo ldconfig
cd /home/pi/
rm -rf libirecovery/
```

**Comment by gilshahar7** [comment]
that did the trick, wondering why it did not install those when i updated from the webUI.

Thanks again for everything <3

**Comment by raspberryenvoie** [comment]
Cool! You're welcome :)
