### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by finnie2006** [raspberryenvoie/piRa1n#4]
How to remove it i shearhed really long but i cant find. i need to do inmportant stuff with my pi now but the web client is also still installed

**Comment by raspberryenvoie** [comment]
This should help you. https://github.com/raspberryenvoie/piRa1n/wiki/Uninstall

**Comment by finnie2006** [comment]
Yes I will close the Ticket
Thanks

**Comment by raspberryenvoie** [comment]
You're welcome :)
