### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by ibrahimk157** [raspberryenvoie/piRa1n#6]
Hello,

Is there any way this could be adapted to run on the Apple M1 CPU (which runs on ARM64)?

since currently there isn’t a single bootable OS for ARM64 CPUs with checkra1n built in. 

I was thinking of running it as a VM on my M1 mac as the current checkra1n Mac version doesn’t work on ARM64.

I’ve been using this on my RPi 4 for quite some time and it’s been great!

thanks

**Comment by raspberryenvoie** [comment]
Hi!
Booting Linux on an M1 mac isn't as simple as on an Intel mac. But it's possible! Check this link out https://corellium.com/blog/linux-m1

Since I don't own an M1 Mac, I'm not sure you'll be able to boot the piRa1n-OS image successfully. Actually piRa1n-OS is based on the arm version of Raspbian not the arm64 version.

If you can't boot piRa1n-OS, you could boot Ubuntu as explained in Corellium's guide. Then, simply download the arm64 checkra1n binary and run it. This should work.

Glad you've enjoyed using piRa1n!

Let me know if you find a solution. Have a nice day :)

**Comment by ibrahimk157** [comment]
> Hi!
> Booting Linux on an M1 mac isn't as simple as on an Intel mac. But it's possible! Check this link out https://corellium.com/blog/linux-m1
> 
> Since I don't own an M1 Mac, I'm not sure you'll be able to boot the piRa1n-OS image successfully. Actually piRa1n-OS is based on the arm version of Raspbian not the arm64 version.
> 
> If you can't boot piRa1n-OS, you could boot Ubuntu as explained in Corellium's guide. Then, simply download the arm64 checkra1n binary and run it. This should work.
> 
> Glad you've enjoyed using piRa1n!
> 
> Let me know if you find a solution. Have a nice day :)

I’ve already tried running the existing piRa1n image on a VM on the M1 mac, and it does not boot at all!

I’ve also already successfully booted Ubuntu on a VM as well. However, for some odd reason, the network functionality of all my VMs (including Windows on ARM) stopped working (even when re-installing everything including Parallels). Making it impossible to install checkra1n through the command line.

So I downloaded the checkra1n ARM64 binary from MacOS, then transferred it to the Ubuntu VM... and running it did absolutely NOTHING.  

And the checkra1n MacOS x86_64 binary does run thanks to Rosetta 2, but it can’t successfully run the jailbreak (it’s completely broken on the M1 macs according to the r/jailbreak community members).

That’s why I wanted an OS that’s ready to boot with checkra1n pre-installed... and the only ARM based OS that I could think of which has that is piRa1n... that’s why I’m here haha.

But anyways now that I know that it’s not that easy to make it work on the M1 macs, I will proceed with closing this issue as it wouldn’t be worth all the time and effort.

**Comment by raspberryenvoie** [comment]
Good news! Checkra1n now supports your mac!
